# Generated by Django 3.1.1 on 2020-10-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_closebid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloseBid',
        ),
    ]
