# Generated by Django 3.1.1 on 2020-11-12 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201110_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
