# Generated by Django 3.1.1 on 2020-11-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='following_id',
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
