# Generated by Django 3.1.1 on 2020-11-17 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('category', models.CharField(blank=True, choices=[('LIST', 'List'), ('BOOKS', 'Books'), ('MOVIES', 'Movies'), ('SPORTS', 'Sports')], max_length=64, null=True, verbose_name='category')),
                ('timeStamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('share', models.ManyToManyField(blank=True, related_name='share', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='item title')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link URL')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('active', models.BooleanField(default=True)),
                ('l_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_item', to='packList.my_list')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_comment', to='packList.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
