# Generated by Django 3.1.1 on 2020-11-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packList', '0002_comments_item_my_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
