# Generated by Django 3.1.1 on 2020-11-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packList', '0003_auto_20201117_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='multi',
            field=models.CharField(default=1, max_length=120, verbose_name='multi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.CharField(default=1, max_length=150, verbose_name='text'),
            preserve_default=False,
        ),
    ]
